<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>xtm</string>
	</array>
	<key>name</key>
	<string>Extempore</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.extempore</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(;).*$\n?</string>
			<key>name</key>
			<string>comment.line.semicolon.extempore</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.function-type.extempore</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.extempore</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\((define|bind-func)(\s+)((\w|\-|\!|\?)+)</string>
			<key>name</key>
			<string>meta.function.extempore</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.function-type.extempore</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.extempore</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>support.type.extempore</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\((bind-alias|bind-type|bind-val)(\s+)((\w|\-|\!|\?)+)(\s+)(([^ 	\)])+)</string>
			<key>name</key>
			<string>meta.type.binding.extempore</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.constant.extempore</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(#)(\w|[\\+-=&lt;&gt;'"&amp;#])+</string>
			<key>name</key>
			<string>constant.character.extempore</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.variable.extempore</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.variable.extempore</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\*)(\S*)(\*)</string>
			<key>name</key>
			<string>variable.other.global.extempore</string>
		</dict>
		<dict>
			<key>match</key>
			<string>:([^ 	\)])+</string>
			<key>name</key>
			<string>support.type.extempore</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(case|do|dotimes|let|letrec|if|else|and|or|not)\b</string>
			<key>name</key>
			<string>keyword.control.extempore</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(set!|pset!|pref|pref-ptr|tset!|tref|tref-ptr|tfill!|aset!|aref|aref-ptr|afill!|vset!|vref|vref-ptr|vfill!)\s</string>
			<key>name</key>
			<string>keyword.getset.extempore</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(=|&lt;&gt;|&lt;=|&gt;=)</string>
			<key>name</key>
			<string>support.equality.extempore</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(null|nil)\b</string>
			<key>name</key>
			<string>constant.language.extempore</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(cons|car|cdr|cond|lambda|quote|eval|append|list|vector|member|load|begin|map|apply|for-each)\b</string>
			<key>name</key>
			<string>support.function.extempore</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b((0(x|X)[0-9a-fA-F]*)|(([0-9]+\.?[0-9]*)|(\.[0-9]+))((e|E)(\+|-)?[0-9]+)?)(L|l|UL|ul|u|U|F|f|ll|LL|ull|ULL)?\b</string>
			<key>name</key>
			<string>constant.numeric.extempore</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.extempore</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.extempore</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.extempore</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.extempore</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.extempore</string>
	<key>uuid</key>
	<string>f429bbaf-0876-4820-8b1c-12a6e234717e</string>
</dict>
</plist>
